<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>scopeName</key>
	<string>source.ebuild</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#eapi_function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.shell</string>
		</dict>
	</array>
	<key>name</key>
	<string>Ebuild</string>
	<key>fileTypes</key>
	<array>
		<string>ebuild</string>
	</array>
	<key>uuid</key>
	<string>c5418506-a7b0-4b25-a013-2fb4d1d7107c</string>
	<key>repository</key>
	<dict>
		<key>eapi_function</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.source.ebuild</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(unpack|econf|emake|einstall|into|insinto|exeinto|docinto|insopts|diropts|exeopts|libopts|dobin|doconfd|dodir|dodoc|doenvd|doexe|dohard|dohtml|doinfo|doinitd|doins|dolib|dolib\.a|dolib\.so|doman|domo|dosbin|dosym|fowners|fperms|keepdir|newbin|newconfd|newdoc|newenvd|newexe|newinitd|newins|newlib\.a|newlib\.so|newman|newsbin|einfo|einfon|elog|ewarn|eerror|ebegin|eend|epause|ebeep|eqawarn|use|useq|usev|use_enable|use_with|has|hasq|hasv|best_version|has_version|addread|addwrite|adddeny|addpredict)\b</string>
			<key>comment</key>
			<string>EAPI function</string>
			<key>name</key>
			<string>meta.eapi-function.source.ebuild</string>
		</dict>
	</dict>
</dict>
</plist>
