<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Provided packages</string>
    <key>uuid</key>
    <string>f7663e5f-cecb-42ca-b228-46320281a61f</string>
    <key>scopeName</key>
    <string>text.package-provided</string>
    <key>fileTypes</key>
    <array>
      <string>package.provided</string>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>comment</key>
        <string>Comment</string>
        <key>name</key>
        <string>comment.line.number-sign.text.package-provided</string>
        <key>match</key>
        <string>#.*$</string>
      </dict>
      <key>atom</key>
      <dict>
        <key>comment</key>
        <string>Atom</string>
        <key>name</key>
        <string>meta.atom.text.package-provided</string>
        <key>match</key>
        <string>((\*|[a-z][0-9a-z]+)(-(\*|[a-z]+))?)(/)((\*|([A-Za-z](-[A-Za-z_+]+|[0-9A-Za-z_+])*))(-[0-9*]+(\.[0-9*]+)*[a-z]?(_[a-z*]+[0-9*]+)?(-r[0-9]+)?))((::)([A-Za-z][-0-9A-Za-z_]*))?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.text.package-provided</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.text.package-provided</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.text.package-provided</string>
          </dict>
          <key>10</key>
          <dict>
            <key>name</key>
            <string>constant.character.text.package-provided</string>
          </dict>
          <key>15</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.text.package-provided</string>
          </dict>
          <key>16</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.text.package-provided</string>
          </dict>
        </dict>
      </dict>
    </dict>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#atom</string>
      </dict>
    </array>
  </dict>
</plist>