<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Packages</string>
    <key>uuid</key>
    <string>36c56ac0-2668-4a78-a306-7ac12dfd480c</string>
    <key>scopeName</key>
    <string>text.packages</string>
    <key>fileTypes</key>
    <array>
      <string>packages</string>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>comment</key>
        <string>Comment</string>
        <key>name</key>
        <string>comment.line.number-sign.text.packages</string>
        <key>match</key>
        <string>#.*$</string>
      </dict>
      <key>atom</key>
      <dict>
        <key>comment</key>
        <string>Atom</string>
        <key>name</key>
        <string>meta.atom.text.packages</string>
        <key>match</key>
        <string>(\*?)((&lt;|&gt;)?=|(&lt;|&gt;))?((\*|[a-z][0-9a-z]+)(-(\*|[a-z]+))?)(/)((\*|([A-Za-z](-[A-Za-z_+]+|[0-9A-Za-z_+])*))(-[0-9*]+(\.[0-9*]+)*[a-z]?(_[a-z*]+[0-9*]+)?(-r[0-9]+)?)?)((::)([A-Za-z][-0-9A-Za-z_]*))?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.text.package-use</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.text.package-use</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.text.package-use</string>
          </dict>
          <key>9</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.text.package-use</string>
          </dict>
          <key>10</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.text.package-use</string>
          </dict>
          <key>14</key>
          <dict>
            <key>name</key>
            <string>constant.character.text.package-use</string>
          </dict>
          <key>19</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.text.package-use</string>
          </dict>
          <key>20</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.text.package-use</string>
          </dict>
        </dict>
      </dict>
    </dict>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#atom</string>
      </dict>
    </array>
  </dict>
</plist>