<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>scopeName</key>
	<string>text.package-use-force</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#atom</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#use</string>
		</dict>
	</array>
	<key>name</key>
	<string>Per-package USE flag forcing</string>
	<key>fileTypes</key>
	<array>
		<string>package.use.force</string>
		<string>package.use.stable.force</string>
	</array>
	<key>uuid</key>
	<string>8b6c7b4b-0f68-451a-a878-d8f6d9f6603c</string>
	<key>repository</key>
	<dict>
		<key>use</key>
		<dict>
			<key>match</key>
			<string>-?[A-Za-z][-0-9A-Za-z_]*</string>
			<key>comment</key>
			<string>USE flag</string>
			<key>name</key>
			<string>entity.other.attribute-name.text.package-use-force</string>
		</dict>
		<key>atom</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>20</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.text.package-use-force</string>
				</dict>
				<key>13</key>
				<dict>
					<key>name</key>
					<string>constant.character.text.package-use-force</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.text.package-use-force</string>
				</dict>
				<key>19</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.text.package-use-force</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.text.package-use-force</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.text.package-use-force</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.text.package-use-force</string>
				</dict>
				<key>23</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.text.package-use-force</string>
				</dict>
				<key>22</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.text.package-use-force</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((&lt;|&gt;)?=|(&lt;|&gt;))?((\*|[a-z][0-9a-z]+)(-(\*|[a-z]+))?)(/)((\*|([A-Za-z](-[A-Za-z_+]+|[0-9A-Za-z_+])*))(-[0-9*]+(\.[0-9*]+)*[a-z]?(_[a-z*]+[0-9*]+)?(-r[0-9]+)?)?)(((:)([A-Za-z][-0-9A-Za-z_/.]*))?)((::)([A-Za-z][-0-9A-Za-z_]*))?</string>
			<key>comment</key>
			<string>Atom</string>
			<key>name</key>
			<string>meta.atom.text.package-use-force</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>#.*$</string>
			<key>comment</key>
			<string>Comment</string>
			<key>name</key>
			<string>comment.line.number-sign.text.package-use-force</string>
		</dict>
	</dict>
</dict>
</plist>
