<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Per-package USE flags</string>
    <key>uuid</key>
    <string>22739b48-7c8a-4cf7-b767-61cc4cb98b79</string>
    <key>scopeName</key>
    <string>text.package-use</string>
    <key>fileTypes</key>
    <array>
      <string>package.use</string>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>comment</key>
        <string>Comment</string>
        <key>name</key>
        <string>comment.line.number-sign.text.package-use</string>
        <key>match</key>
        <string>#.*$</string>
      </dict>
      <key>atom</key>
      <dict>
        <key>comment</key>
        <string>Atom</string>
        <key>name</key>
        <string>meta.atom.text.package-use</string>
        <key>match</key>
        <string>((&lt;|&gt;)?=|(&lt;|&gt;))?((\*|[a-z][0-9a-z]+)(-(\*|[a-z]+))?)(/)((\*|([A-Za-z](-[A-Za-z_+]+|[0-9A-Za-z_+])*))(-[0-9*]+(\.[0-9*]+)*[a-z]?(_[a-z*]+[0-9*]+)?(-r[0-9]+)?)?)((::)([A-Za-z][-0-9A-Za-z_]*))?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.text.package-use</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.text.package-use</string>
          </dict>
          <key>8</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.text.package-use</string>
          </dict>
          <key>9</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.text.package-use</string>
          </dict>
          <key>13</key>
          <dict>
            <key>name</key>
            <string>constant.character.text.package-use</string>
          </dict>
          <key>18</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.text.package-use</string>
          </dict>
          <key>19</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.text.package-use</string>
          </dict>
        </dict>
      </dict>
      <key>use</key>
      <dict>
        <key>comment</key>
        <string>USE flag</string>
        <key>name</key>
        <string>entity.other.attribute-name.text.package-use</string>
        <key>match</key>
        <string>(-?[A-Za-z][-0-9A-Za-z_]*)</string>
      </dict>
    </dict>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#atom</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#use</string>
      </dict>
    </array>
  </dict>
</plist>